# Generated by Django 3.0.7 on 2020-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('signer_name', models.CharField(max_length=100, verbose_name='签收人')),
                ('signer_mobile', models.CharField(max_length=100, verbose_name='签收电话')),
                ('province', models.CharField(default='', max_length=200, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=200, verbose_name='城市')),
                ('district', models.CharField(max_length=200, verbose_name='区域')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '求购'), (5, '售后')], default=1, verbose_name='留言类型')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('message', models.TextField(verbose_name='留言')),
                ('file', models.FileField(upload_to='', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
            },
        ),
    ]
